[tool.poetry]
name = "liquidityfreak"
description = ""
authors = ["sp33dfre4k <sp33dfre4k@skiff.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
web3 = "^6.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
